# Generated by Django 5.1.2 on 2024-11-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_forts_delete_fort_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latitude_longitude',
            name='destination_latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='latitude_longitude',
            name='destination_longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='latitude_longitude',
            name='origin_latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='latitude_longitude',
            name='origin_longitude',
            field=models.FloatField(null=True),
        ),
    ]
