# Generated by Django 5.1.2 on 2024-11-02 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_latitude_longitude_destination_latitude_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forts',
            options={'ordering': ['-fort_id']},
        ),
    ]
