# Generated by Django 5.1.2 on 2024-11-03 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_forts_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forts',
            options={'ordering': ['fort_id']},
        ),
        migrations.AlterModelOptions(
            name='latitude_longitude',
            options={'ordering': ['plan_id']},
        ),
        migrations.AlterModelOptions(
            name='result',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='user_location',
            options={'ordering': ['u_id']},
        ),
        migrations.AlterField(
            model_name='forts',
            name='fort_latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='forts',
            name='fort_longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='latitude_longitude',
            name='destination_latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='latitude_longitude',
            name='destination_longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='latitude_longitude',
            name='origin_latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='latitude_longitude',
            name='origin_longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='user_location',
            name='user_latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='user_location',
            name='user_longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
    ]
