# Generated by Django 5.1.2 on 2024-11-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_forts_options_alter_latitude_longitude_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='all_trips',
            fields=[
                ('trip_id', models.AutoField(primary_key=True, serialize=False)),
                ('trip_district', models.CharField(max_length=50)),
                ('forts_visited', models.CharField(max_length=50)),
                ('required_time', models.CharField(max_length=100)),
                ('minimum_cost', models.FloatField(blank=True, null=True)),
                ('date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='forts',
            name='fort_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forts',
            name='fort_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='latitude_longitude',
            name='destination_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='latitude_longitude',
            name='destination_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='latitude_longitude',
            name='origin_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='latitude_longitude',
            name='origin_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_location',
            name='user_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_location',
            name='user_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
