# Generated by Django 5.1.2 on 2024-11-04 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_all_trips_alter_forts_fort_latitude_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='all_trips',
        ),
    ]
