# Generated by Django 5.1.2 on 2024-11-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='curr_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='curr_log',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
