# Generated by Django 5.1.2 on 2024-11-08 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_userdata_curr_lat_alter_userdata_curr_log'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserGeneratedPlans',
        ),
    ]
