# Generated by Django 5.1.2 on 2024-11-04 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='all_trips',
            fields=[
                ('trip_id', models.AutoField(primary_key=True, serialize=False)),
                ('trip_district', models.CharField(max_length=50)),
                ('forts_visited', models.CharField(max_length=50)),
                ('required_time', models.CharField(max_length=100)),
                ('minimum_cost', models.FloatField(blank=True, null=True)),
                ('date', models.DateField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_trips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='all_recommendations',
            fields=[
                ('recommendation_id', models.AutoField(primary_key=True, serialize=False)),
                ('trip_title', models.CharField(max_length=150)),
                ('trip_details', models.TextField()),
                ('image_name', models.ImageField(upload_to='img')),
                ('trip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommend_trip', to='recommendations.all_trips')),
            ],
        ),
    ]
