# Generated by Django 5.1.2 on 2024-11-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_remove_all_recommendations_trip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_recommendations',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='all_recommendations',
            name='image_name',
            field=models.ImageField(upload_to='img/recomendation_imgs'),
        ),
    ]
