# Generated by Django 5.1.2 on 2024-11-22 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0004_all_trips_user_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_trips',
            name='forts_visited',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='all_trips',
            name='trip_district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='all_trips',
            name='user_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
