# Generated by Django 5.1.2 on 2024-11-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0005_alter_all_trips_forts_visited_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_recommendations',
            name='image_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
